# -*- coding: utf-8 -*-
"""Get Partitions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B-8tyiI8fM8G5SbGf1R-w_0rBLdqsyr6
"""

from google.colab import drive
drive.mount("/content/gdrive")

!pip install datasets

from datasets import Dataset
df = Dataset.from_csv("/content/gdrive/My Drive/df_clean_wo_embeddings.csv")

import math

len = df.num_rows
len_partition = math.floor(len/6)
partition_1 = np.arange(len_partition)
partition_2 = np.arange(len_partition, 2*len_partition, 1)
partition_3 = np.arange(2*len_partition, 3*len_partition, 1)
partition_4 = np.arange(3*len_partition, 4*len_partition, 1)
partition_5 = np.arange(4*len_partition, 5*len_partition, 1)
partition_6 = np.arange(5*len_partition, len, 1)

partitions = [partition_1, partition_2, partition_3, partition_4, partition_5, partition_6]
for partition in partitions:
  print(partition)

df_1 = df.select(partition_1)
df_2 = df.select(partition_2)
df_3 = df.select(partition_3)
df_4 = df.select(partition_4)
df_5 = df.select(partition_5)
df_6 = df.select(partition_6)

df_1.to_csv('df_part_sit.csv')
df_2.to_csv('df_part_par.csv')
df_3.to_csv('df_part_jen.csv')
df_4.to_csv('df_part_atr.csv')
df_5.to_csv('df_part_mug.csv')
df_6.to_csv('df_part_zoe.csv')

df_pd_1 = pd.read_csv('df_part_sit.csv')
df_pd_2 = pd.read_csv('df_part_par.csv')
df_pd_3 = pd.read_csv('df_part_jen.csv')
df_pd_4 = pd.read_csv('df_part_atr.csv')
df_pd_5 = pd.read_csv('df_part_mug.csv')
df_pd_6 = pd.read_csv('df_part_zoe.csv')

df_pd_1.drop(['Unnamed: 0','Unnamed: 0.1'], axis=1, inplace=True)
df_pd_2.drop(['Unnamed: 0','Unnamed: 0.1'], axis=1, inplace=True)
df_pd_3.drop(['Unnamed: 0','Unnamed: 0.1'], axis=1, inplace=True)
df_pd_4.drop(['Unnamed: 0','Unnamed: 0.1'], axis=1, inplace=True)
df_pd_5.drop(['Unnamed: 0','Unnamed: 0.1'], axis=1, inplace=True)
df_pd_6.drop(['Unnamed: 0','Unnamed: 0.1'], axis=1, inplace=True)

df_pd_1.to_csv('df_part_sittun.csv')
df_pd_2.to_csv('df_part_parth.csv')
df_pd_3.to_csv('df_part_jenna.csv')
df_pd_4.to_csv('df_part_atrima.csv')
df_pd_5.to_csv('df_part_mugundhan.csv')
df_pd_6.to_csv('df_part_zoe.csv')

!cp df_part_sittun.csv "/content/gdrive/My Drive/partitions"
!cp df_part_parth.csv "/content/gdrive/My Drive/partitions"
!cp df_part_jenna.csv "/content/gdrive/My Drive/partitions"
!cp df_part_atrima.csv "/content/gdrive/My Drive/partitions"
!cp df_part_mugundhan.csv "/content/gdrive/My Drive/partitions"
!cp df_part_zoe.csv "/content/gdrive/My Drive/partitions"